env: dev
log:
  log_level: info
  log_type: loki
loki:
  url: "http://localhost:3100"
  username: "easy"
  password: "easyms"
store_type: local
consul:
  host: "localhost:8500"
  key_path: easyms/%s/%s
  reload_on_changes: true