log:
  log_type: local
  log_level: debug
loki:
  url: http://172.29.16.1:3100/loki/api/v1/push
  username: easy
  password: easymPhase
database:
  type: postgres
  host: 172.29.16.1
  port: 5432
  user: easy
  password: easypass
  database: easydb
  # 连接池配置
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
  conn_max_idle_time: 1800
cache:
  redis:
    address: "172.29.16.1:6379"
    password: "easymspass"
    db: 0
    # 缓存防护配置
    null_cache_expire: 60
    mutex_expire: 10
oauth2:
  jwt_secret: "a-secure-and-long-secret-key-for-dev"
